name: CI/CD
on:
  push:
    branches: ["deploy"]
jobs:
  deploy-server:
    name: deploy-server
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
    - name: 'Run stuff'
      shell: bash
      run: |
        eval $(ssh-agent -s)
        apt-get update -y
        apt-get install -y rsync sshpass
        chmod 400 "$SSH_PRIVATE_KEY"
        ssh-add "$SSH_PRIVATE_KEY"
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        rm -rf server.tar.gz
        cp config-prod.js config.js
        rm -rf output/test output/.tsbuildinfo data/process_data.ts
        tar czf server.tar.gz spirit run.sh
        ssh -oStrictHostKeyChecking=no root@spirit.pokemontcg.app "mkdir -p /apps/spirit"
        scp -oStrictHostKeyChecking=no server.tar.gz root@spirit.pokemontcg.app:/tmp
        ssh -oStrictHostKeyChecking=no root@spirit.pokemontcg.app "cd /apps/spirit && tar xzf /tmp/server.tar.gz && chmod +x set_env.sh && ./run.sh"