name: CI/CD
on:
  push:
    branches: ["deploy"]
jobs:
  deploy-server:
    name: deploy-server
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: production
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
    - name: 'Run stuff'
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        rm -rf server.tar.gz
        rm -rf output/test output/.tsbuildinfo data/process_data.ts
        tar czf server.tar.gz spirit run.sh requirements.txt re_tools
        ssh -i ~/.ssh/deploy_key -oStrictHostKeyChecking=no root@spirit.pokemontcg.app "mkdir -p /apps/spirit"
        scp -i ~/.ssh/deploy_key -oStrictHostKeyChecking=no server.tar.gz root@spirit.pokemontcg.app:/tmp
        ssh -i ~/.ssh/deploy_key -oStrictHostKeyChecking=no root@spirit.pokemontcg.app "cd /apps/spirit && tar xzf /tmp/server.tar.gz && chmod +x run.sh && sudo chown www-data:www-data /var/cache/spirit_assets && sudo nginx -t && sudo systemctl reload nginx" && sudo SPIRIT_HTTP_PORT=8001 SPIRIT_PUBLIC_HOST=192.210.136.108 bash run.sh